try { console.log('[ATP][LOAD] config.js carregado com sucesso'); } catch (e) { }

'use strict';

const LOG_PREFIX = '[ATP]';
const TABLE_ID = 'tableAutomatizacaoLocalizadores';
let onlyConflicts = false;
const ATP_VERSION = '10.66';

const tipoRank = {
  'Regra em Duplicidade': 5,
  'Looping': 5,
  'Potencial Looping': 5,
  'Filtros Conflitantes': 5,
  'Regra sem Finalidade': 4,
  'Prioridade Invertida': 3,
  'Avaliar Prioridade': 2,
  'Prioridade Correta': 1
};

const impactoRank = {
  'Alto': 3,
  'Médio': 2,
  'Baixo': 1
};

const ATP_CONFIG = {
  analisarLooping: false,
  analisarPerdaObjetoCondicional: true,
  analisarQuebraFluxo: true,
  incluirRegrasInativas: false,
  localizadoresSistema: {
    ids: [],
    nomes: [
      'AG. DIGITALIZAÇÃO',
      'AGRAVO',
      'ALV SOLT CUMPRIDO',
      'ALV SOLT CUMPRIDO EM TERMOS',
      'ALV SOLT DEVOLVIDO',
      'ALV SOLT INFORMAÇÃO',
      'ALV SOLT LIDO',
      'APRECIACAO_JUDIC',
      'AR ENTREGUE',
      'AR NÃO ENTREGUE',
      'ARQUIVO',
      'AUDIÊNCIA CONC. CANCELADA',
      'BAIXADOS',
      'BNMP REC',
      'BNMP RGL',
      'CANCELAMENTO',
      'CARGA_ADVOGADO',
      'CARTA AR ENVIADA',
      'CARTA AR PAGAMENTO CONFIRMADO',
      'CARTA AR PAGAMENTO NÃO REALIZADO',
      'CARTAS Pr Or Rog',
      'CEJUSCON-RECB',
      'CENTRAL DE MANDADOS',
      'CESSADO SOBRESTAMENTO',
      'CI NÃO PAGAS',
      'CI PEND',
      'CITACAO DJE NÃO CONFIRMADA',
      'COMUNICA TRÂNSITO',
      'CONCILIAÇÃO',
      'CONCILIACAO_COM_ACOR',
      'CONCILIACAO_ENCERRAD',
      'CONCILIACAO_INICIADA',
      'CONCILIACAO_SEM_ACOR',
      'Conta +1Ano c Saldo Baixado',
      'Conta +1Ano c Saldo Movimento',
      'CONTADORIA',
      'CORREGEDORIA',
      'CR NÃO PAGAS',
      'CR PEND',
      'CUSTAS-PEND',
      'CUSTAS-VENC',
      'DECLINAÇÃO COMPETÊNCIA',
      'DECURSO DE PRAZO',
      'DEPÓSITO JUDICIAL',
      'DEVOL-DILIGÊNCIA',
      'DEVOLUCAO TURMA',
      'DEVOLVIDOS JEE',
      'DEVOLVIDOS OFICIAL DE JUSTIÇA',
      'DIGITALIZADOS',
      'DILAÇÃO DE PRAZO PF',
      'DIST',
      'EF-CITACAO-CORREIO',
      'EF-CITACAO-MANDADO',
      'EMBDEC',
      'EMBINFR',
      'ENT. SEM PROC.',
      'ERRO-INTIMAÇÃO-RESTITUIÇÃO-CUSTAS',
      'ERRO_AGENDAMENTO_EVENTO',
      'ERRO_ENVIO_INTIMACAO_DJEN',
      'ERRO_INTIMA_AUTOMATI',
      'FÓRUM HABILITADO',
      'IMPEDIMENTOS',
      'INCAPAZ ACIDENTE DE TRABALHO',
      'INTIMA POL CIENT',
      'LAUDO COMPLEMENTAR',
      'LAUDO INCAPAZ CIVIL',
      'LAUDO INCAPAZ PERM',
      'LAUDO INCAPAZ PRET',
      'LAUDO INCAPAZ REDUZ',
      'LAUDO INCAPAZ TEMP',
      'LAUDO PERICIAL CAPAZ',
      'MAND CUMPRIDO',
      'MAND CUMPRIDO HORA CERTA',
      'MAND MOVIMENTADO',
      'MAND PARC CUMPRIDO',
      'MAND PRISÃO INFORMAÇÃO',
      'MAND SEM CUMPRIMENTO',
      'MIGRADOS',
      'MIGRADOS_SANEAMENTO',
      'NOVA PARTE CONFRONTANTE',
      'NOVA PARTE HERDEIRO',
      'NOVA PARTE TESTEMUNHA',
      'PARECER MPF',
      'PEDIDO ARQ. MPF',
      'PEDIDO DE TED AUTOMÁTICO',
      'PEDIDO DE UNIFORMIZAÇÃO',
      'PEDIDO DECL. COMP.',
      'PERITO IMPEDIDO/SUSP',
      'PET INIC HC TR',
      'PETIÇÃO',
      'PETIÇÃO INI CAUTELAR',
      'PETIÇÃO INI CRIMINAL',
      'PETIÇÃO INICIAL',
      'PETIÇÃO INICIAL JEE',
      'PETIÇÃO INICIAL MS',
      'PETIÇÃO INICIAL TR',
      'PETIÇÃO URGENTE',
      'PI - DEPENDÊNCIA',
      'PLANTÃO',
      'PROC ADV',
      'PROCESSOS CRIMINAIS P/ REDIST.',
      'PROCESSOS P/ REDISTRIBUIR',
      'PROCESSOS SEM ADV',
      'REATIVADOS',
      'REC PRESIDENCIA TR',
      'RECEBIDOS',
      'RECEBIDOS MUTIRÃO',
      'RECEBIDOS TR',
      'RECEBIDOS-DIL./CONC.',
      'RECEBIDOS_CECON',
      'RECEBIDOS_CECON_URGENTES',
      'RECURSO EXTRAORDINÁR',
      'REDISTRIBUÍDO',
      'REGISTRO DE ÓBITO',
      'REL-EXEC-PENAL',
      'REL-PSC-CONCLUÍDA',
      'REL-PSC-INSUFICIENTE',
      'REQ - INTIMADA',
      'REQ - PAGA',
      'REQ - PAGA - BLOQUEADA',
      'REQ - PAGA - LIBERADA',
      'REQ - PREP. TRANSM.',
      'REQ - PROCESSADA',
      'REQ - SUPERPREFERENCIAL - PAGA - BLOQUEADA',
      'REQ - SUPERPREFERENCIAL - PAGA - LIBERADA',
      'REQ - SUPERPREFERENCIAL - PROCESSADA',
      'REQ.PAG.CANCELADA',
      'RESINSS-CANCELADAS',
      'RESINSS-CONCLUÍDO',
      'RESINSS-EM-FILA',
      'RESINSS-EM-RESSARCIMENTO',
      'RESINSS-ERRO',
      'RESTRITO AO JUIZ',
      'SEM CONCILIAÇÃO',
      'SERASAJUD-INSERÇÃO',
      'SERASAJUD-RETIRADA',
      'SIDEJUD_AG.CONF_TRANSFERENCIA',
      'SIDEJUD_ALVARA_ASS',
      'SISBAJUD-SOLICITADA-DEVOLUO',
      'SPC-INSERÇÃO',
      'SPC-RETIRADA',
      'STF-DIST',
      'STF-RECEBIDOS',
      'STF-REM',
      'STJ-RECEBIDOS',
      'STJ-REM',
      'Suspensão/Feriado Retroativo',
      'SUSPENSOS',
      'SUSPENSOS-RETORNO',
      'TJSP-AGRAVO INTERPOSTO',
      'TJSP-RECEBIDOS',
      'TJSP-REMETIDOS',
      'TJSP-TRÂNSITO',
      'TJSP-TRÂNSITO',
      'TJSP/TR-BAIXADOS',
      'TJSP/TR-DECISÃO',
      'TJSP/TR-JULGADOS',
      'TRÂNSITO EM JULGADO',
      'TRF-AGRAVO RETIDO',
      'TRF-RECEBIDOS',
      'TRF-REMETIDOS',
      'TU REC',
      'TU REM',
      'URGENTE',
      'URGENTE JEE',
      'VALIDAR PODERES PROC',
      'VERIFICAR ASSUNTO',
      'VERIFICAR PARTES',
      'VERIFICAR PROCURADOR',
      'VISTA ADV PROCESSO'
    ],
    descricoes: [
      'AGUARDA DIGITALIZAÇÃO',
      'AGRAVO',
      'ALVARÁ DE SOLTURA CUMPRIDO',
      'ALVARÁ DE SOLTURA CUMPRIDO EM TERMOS',
      'ALVARÁ DE SOLTURA DEVOLVIDO SEM CUMPRIMENTO',
      'ALVARÁ DE SOLTURA INFORMAÇÃO',
      'ALVARÁ DE SOLTURA LIDO',
      'APRECIAÇÃO JUDICIAL',
      'CARTA AR ENTREGUE',
      'CARTA AR NÃO ENTREGUE',
      'ARQUIVO',
      'AUDIÊNCIA CONC. CANCELADA',
      'BAIXADOS',
      'BNMP RECEBIDOS',
      'REGULARIZAR BNMP',
      'VERIFICAR CANCELAMENTO EVENTO',
      'CARGA ADVOGADO',
      'CARTA AR ENVIADA',
      'CARTA AR PAGAMENTO CONFIRMADO',
      'CARTA AR PAGAMENTO NÃO REALIZADO',
      'CARTAS Pr Or Rog',
      'CEJUSCON-RECEBIDOS',
      'CENTRAL DE MANDADOS',
      'CESSADO SOBRESTAMENTO',
      'CUSTAS INICIAIS NÃO PAGAS',
      'CUSTAS INICIAIS PEND',
      'Citação DJE Não Confirmada',
      '1ºG-COMUNICA TRÂNSITO',
      'CONCILIAÇÃO',
      'CONCILIACAO_COM_ACORDO',
      'CONCILIACAO ENCERRADA',
      'CONCILIACAO INICIADA',
      'CONCILIACAO_SEM_ACORDO',
      'Conta Req +1Ano com Saldo - BAIXADO',
      'Conta Req +1Ano com Saldo - MOVIMENTO',
      'CONTADORIA',
      'CORREGEDORIA',
      'CUSTAS RECURSAIS NÃO PAGAS',
      'CUSTAS RECURSAIS PEN',
      'CUSTAS PENDENTES',
      'CUSTAS VENCIDAS',
      'DECLINAÇÃO COMPETÊNCIA',
      'DECURSO DE PRAZO',
      'DEPÓSITO JUDICIAL',
      'DEVOLVIDOS JEE - DILIGÊNCIA',
      'DEVOLUCAO TURMA',
      'DEVOLVIDOS JEE',
      'DEVOLVIDOS OFICIAL DE JUSTIÇA',
      'DIGITALIZADOS',
      'PEDIDO DE DILAÇÃO DE PRAZO PF',
      'DISTRIBUIÇÃO',
      'EF CITAÇÃO POR CORREIO',
      'EF CITAÇÃO POR MANDADO',
      'EMBARGOS DE DECLARAÇÃO',
      'EMBARGOS INFRINGENTES',
      'ENT. SEM PROCURADOR',
      'ERRO INTIMAÇÃO RESTITUIÇÃO CUSTAS',
      'ERRO_AGENDAMENTO_EVENTO',
      'ERRO_ENVIO_INTIMACAO_DJEN',
      'ERRO_INTIMA_AUTOMATICO',
      'FÓRUM HABILITADO',
      'IMPEDIMENTOS',
      'INCAPAZ ACIDENTE DE TRABALHO',
      'INTIMA POLICIA CIENTIFICA',
      'LAUDO COMPLEMENTAR',
      'LAUDO INCAPAZ CIVIL',
      'LAUDO INCAPAZ PERM',
      'LAUDO INCAPAZ PRET',
      'LAUDO INCAPAZ REDUZ',
      'LAUDO INCAPAZ TEMP',
      'LAUDO PERICIAL CAPAZ',
      'MANDADO CUMPRIDO',
      'MANDADO CUMPRIDO HORA CERTA',
      'MANDADO MOVIMENTADO',
      'MANDADO PARCIALMENTE CUMPRIDO',
      'MANDADO DE PRISÃO INFORMAÇÃO',
      'MANDADO SEM CUMPRIMENTO',
      'MIGRADOS',
      'MIGRADOS_SANEAMENTO',
      'NOVA PARTE CONFRONTANTE',
      'NOVA PARTE HERDEIRO',
      'NOVA PARTE TESTEMUNHA',
      'PARECER MPF',
      'PEDIDO ARQUIVAMENTO MPF',
      'PEDIDO DE TED AUTOMÁTICO',
      'PEDIDO DE UNIFORMIZAÇÃO',
      'PEDIDO DECLINAÇÃO COMPETÊNCIA',
      'PERITO IMPEDIDO OU SUSPEITO',
      'PETIÇÃO INICIAL HC TR',
      'PETIÇÃO',
      'PETIÇÃO INICIAL CAUTELAR',
      'PETIÇÃO INICIAL CRIMINAL',
      'PETIÇÃO INICIAL',
      'PETIÇÃO INICIAL JEE',
      'PETIÇÃO INICIAL MS',
      'PETIÇÃO INICIAL TR',
      'PETIÇÃO URGENTE',
      'PI - DEPENDÊNCIA',
      'PLANTÃO',
      'PROCURAÇÃO ADV',
      'PROCESSOS CRIMINAIS P/ REDISTRIBUIR',
      'PROCESSOS P/ REDISTRIBUIR',
      'PROCESSOS SEM ADVOGADO',
      'REATIVADOS',
      'REC PRESIDENCIA TR',
      'RECEBIDOS',
      'RECEBIDOS MUTIRÃO',
      'RECEBIDOS TR',
      'RECEBIDOS-DILIG./CONCIL.',
      'RECEBIDOS CECON',
      'RECEBIDOS CECON URGENTES',
      'RECURSO EXTRAORDINÁRIO',
      'REDISTRIBUÍDO',
      'REGISTRO DE ÓBITO',
      'REL PSC EXEC PENAL',
      'RELATÓRIO PSC CONCLUÍDA',
      'RELATÓRIO PSC INSUFICIENTE',
      'REQ - INTIMADA',
      'REQ - PAGA',
      'REQ - PAGA - BLOQUEADA',
      'REQ - PAGA - LIBERADA',
      'REQ - PREPARADA TRANSMISSÃO',
      'REQ - PROCESSADA',
      'REQ - SUPERPREFERENCIAL - PAGA - BLOQUEADA',
      'REQ - SUPERPREFERENCIAL - PAGA - LIBERADA',
      'REQ - SUPERPREFERENCIAL - PROCESSADA',
      'REQUISICAO PAGAMENTO CANCELADA',
      'RESINSS-CANCELADAS',
      'RESINSS-CONCLUÍDO',
      'RESINSS-EM-FILA',
      'RESINSS-EM-RESSARCIMENTO',
      'RESINSS-ERRO',
      'RESTRITO AO JUIZ',
      'SEM CONCILIAÇÃO',
      'SERASAJUD-INSERÇÃO',
      'SERASAJUD-RETIRADA',
      'SIDEJUD - ALVARÁ ASSINADO - AG. CONFIRMAÇÃO DA TRANSFERÊNCIA',
      'SIDEJUD - ALVARA PARA ASSINATURA',
      'AUTOMAO SISBAJUD - Solicitada devoluo do processo',
      'SPC-INSERÇÃO',
      'SPC-RETIRADA',
      'STF-Distribuídos',
      'STF-RECEBIDOS',
      'STF REMETIDOS',
      'STJ-RECEBIDOS',
      'STJ REMETIDOS',
      'Suspensão/Feriado Retroativo',
      'PROCESSOS SUSPENSOS',
      'RETORNADOS DE SUSPENSÃO',
      'TJSP-AGRAVO INTERPOSTO',
      'TJSP-RECEBIDOS',
      'TJSP-REMETIDOS',
      'TJSP-TRÂNSITO',
      'TJSP-TRÂNSITO EM JULGADO',
      'TJSP/TR-BAIXADOS',
      'TJSP/TR-DECISÃO',
      'TJSP/TR-JULGADOS',
      'TRÂNSITO EM JULGADO',
      'TRF-AGRAVO RETIDO',
      'TRF-RECEBIDOS',
      'TRF-REMETIDOS',
      'TU RECEBIDOS',
      'TU REMETIDOS',
      'URGENTE',
      'URGENTE JEE',
      'VALIDAR PODERES DA PROCURAÇÃO',
      'VERIFICAR ASSUNTO',
      'VERIFICAR PARTES',
      'VERIFICAR PROCURADOR/ENTIDADE',
      'VISTA ADV PROCESSO'
    ]
  },
  equilibrio: {
    pesos: { acao: 0.6, remover_unidade: 0.25, incluir: 0.15, outros: 0.0 },
    faixa: {
      acao: { L: 0.4, U: 0.6 },
      remover_unidade: { L: 0.3, U: 0.7 },
      incluir: { L: 0.2, U: 0.5 },
      outros: { L: 0.0, U: 0.0 }
    }
  },
  notaExecucao: {
    pesosConflito: { 'Regra em Duplicidade': 3, 'Prioridade Invertida': 1, 'Filtros Conflitantes': 3 },
    pseudoAcertos: 1,
    pseudoErros: 1
  },
  notaEstrutural: {
    pesosPositivos: { remover_unidade: 0.55, acoes_total: 0.30, incluir_distintos: 0.15 },
    pesosNegativos: { remover_sistema: 0.55, triagem: 0.45 },
    escalasPositivas: { remover_unidade: 250, acoes_total: 180, incluir_distintos: 70 },
    escalasNegativas: { remover_sistema: 120, triagem: 160 },
    penalidadeNegativa: 0.35
  },
  notaVolume: {
    escala: 600
  }
};

try {
  if (typeof window.atpIncludeInactiveRules !== 'boolean') {
    window.atpIncludeInactiveRules = !!ATP_CONFIG.incluirRegrasInativas;
  }
} catch (_) { }

// Compatibilidade com versões antigas da UI que consultam esta função.
function isDesativarResultPage() {
  try {
    const href = String((window && window.location && window.location.href) || '');
    if (!/controlador\.php/i.test(href)) return true;
    const acao = String(new URL(href).searchParams.get('acao') || '').toLowerCase();
    if (!acao) return false;
    return acao !== 'automatizar_localizadores';
  } catch (_) {
    return false;
  }
}

try {
  window.isDesativarResultPage = window.isDesativarResultPage || isDesativarResultPage;
  window.isDesactiveResultPage = window.isDesactiveResultPage || isDesativarResultPage;
  window.isDeactivateResultPage = window.isDeactivateResultPage || isDesativarResultPage;
} catch (_) { }

// Monitor de uso (preencher URL/chave para habilitar coleta).
try {
  window.ATP_ACCESS_MONITOR_CONFIG = Object.assign({
    enabled: true,
    // Preencha com os dados do seu projeto Supabase.
    supabaseUrl: 'https://ezkxycrnjwforacfqgzi.supabase.co',
    supabaseApiKey: 'sb_publishable_1eiaDpAcTCwRdQDmxW8oTA_oXgN3xpk',
    tableName: 'atp_execucoes',
    waitMaxMs: 30000
  }, window.ATP_ACCESS_MONITOR_CONFIG || {});
} catch (_) { }

try { console.log('[ATP][OK] config.js inicializado'); } catch (e) { }
